version: '3.3'
services:
    client:
      networks:
       - chatlink_network
      ports:
       - '8080:80'
      container_name: client
      image: 'chatlink/client:latest'

networks:
  chatlink_network:
   external: true
