version: '3.3'
services:
    mongo:
      networks:
       - chatlink_network
      ports:
       - '2717:27017'
      volumes:
       - mongodb:/data/db
      container_name: chatlink_mongo
      image: 'mongo:latest'

volumes:
 mongodb:

networks:
 chatlink_network:
   external: true
