version: '3.3'
services:
    server:
      networks:
       - chatlink_network
      ports:
       - '3000:3000'
       - '3001:3001'
      container_name: server
      image: 'chatlink/server:latest'

networks:
  chatlink_network:
   external: true
